import Head from 'next/head';
import { useMoralis } from 'react-moralis';
import Login from '../components/login/Login';

export default function Home() {
  const { isAuthenticated, logout } = useMoralis();

  return !isAuthenticated ? (
    <Login />
  ) : (
    <div className="bg-body w-screen h-screen">
      <Head>
        <title>META-CHAT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={logout}>logout</button>
    </div>
  );
}
